server:
  port: 8096
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.204.106:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: qwer

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug

#dubbo配置文件    
#dubbo:
#  scan:
#    basePackages: com.jt   #定义包扫描
#  application:
#    name: provider-user    #定义服务名称 必须添加
#  registry:
#    address: zookeeper://101.200.204.106:2181?backup=101.200.204.106:2182,101.200.204.106:2183
#  protocol:    #协议
#    name: dubbo #使用dubbo默认协议
#    port: 20880  #端口号唯一