#server:
#  port: 8094
##项目的发布路径是根目录
#spring:     #定义springmvc视图解析器
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
##dubbo:
##  scan:
##    basePackages: com.jt
##  application:
##    name: consumer-web
##  registry:
##    address: zookeeper://47.116.140.127:2181?backup=47.116.140.127:2182,47.116.140.127:2183