#server:
#  port: 8094
##项目的发布路径是根目录
#spring:     #定义springmvc视图解析器
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
##dubbo:
##  scan:
##    basePackages: com.jt
##  application:
##    name: consumer-web
##  registry:
##    address: zookeeper://101.200.204.106:2181?backup=101.200.204.106:2182,101.200.204.106:2183